<?php
$title = "Pro Forma Invoices";
ob_start();
?>
<div class="row justify-content-center">
    <div class="col-12 col-xxl-11">
        <div class="d-flex justify-content-between flex-wrap align-items-center pt-3 pb-2 mb-3 gap-2">
            <h1 class="h2 mb-0">Pro Forma Invoices</h1>
            <div class="d-flex flex-wrap gap-2 page-header-actions">
                <a href="<?= BASE_URL ?>/proformas/create"
                    class="btn btn-sm btn-primary rounded-pill d-flex align-items-center gap-1 px-3 fw-medium shadow-sm">
                    <span class="material-symbols-outlined" style="font-size: 18px;">add</span> New Pro Forma
                </a>
            </div>
        </div>

        <div class="card shadow-sm border-0 rounded-4 mb-4">
            <div class="table-responsive">
                <table class="table table-hover align-middle mb-0">
                    <thead class="table-light">
                        <tr>
                            <th class="ps-4 text-secondary fw-semibold border-0 py-3" style="width: 50px;">#</th>
                            <th class="text-secondary fw-semibold border-0 py-3">Reference No</th>
                            <th class="text-secondary fw-semibold border-0 py-3">Customer</th>
                            <th class="text-secondary fw-semibold border-0 py-3">Generated By</th>
                            <th class="text-secondary fw-semibold border-0 py-3">Date</th>
                            <th class="text-end text-secondary fw-semibold border-0 py-3">Total Amount</th>
                            <th class="pe-4 text-center text-secondary fw-semibold border-0 py-3">Actions</th>
                        </tr>
                    </thead>
                    <tbody class="border-top-0">
                        <?php if (empty($proformas)): ?>
                            <tr>
                                <td colspan="7" class="text-center py-5 text-muted">
                                    <span class="material-symbols-outlined d-block mb-2" style="font-size: 48px; opacity: 0.5;">receipt_long</span>
                                    No Pro Forma Invoices found.<br>
                                    <a href="<?= BASE_URL ?>/proformas/create" class="btn btn-sm btn-outline-primary mt-3 rounded-pill px-3">Generate First Pro Forma</a>
                                </td>
                            </tr>
                        <?php else: ?>
                            <?php foreach ($proformas as $index => $pf): ?>
                                <tr>
                                    <td class="ps-4 text-muted fw-bold"><?= $index + 1 ?></td>
                                    <td>
                                        <span class="fw-bold text-dark"><?= e($pf['reference_no']) ?></span>
                                    </td>
                                    <td>
                                        <?php if ($pf['customer_name']): ?>
                                            <div class="d-flex align-items-center gap-2">
                                                <div class="bg-primary bg-opacity-10 text-primary rounded-circle d-flex align-items-center justify-content-center fw-bold" style="width: 32px; height: 32px; font-size: 14px;">
                                                    <?= strtoupper(substr(e($pf['customer_name']), 0, 1)) ?>
                                                </div>
                                                <span class="fw-medium text-dark"><?= e($pf['customer_name']) ?></span>
                                            </div>
                                        <?php else: ?>
                                            <span class="text-muted fst-italic">Walk-in</span>
                                        <?php endif; ?>
                                    </td>
                                    <td><?= e($pf['recorder_name'] ?? 'System') ?></td>
                                    <td>
                                        <div class="text-dark"><?= date('M j, Y', strtotime($pf['created_at'])) ?></div>
                                        <small class="text-muted"><?= date('H:i', strtotime($pf['created_at'])) ?></small>
                                    </td>
                                    <td class="text-end fw-bold text-dark">
                                        ₵<?= number_format($pf['total_amount'], 2) ?>
                                    </td>
                                    <td class="pe-4 text-center">
                                        <div class="d-flex justify-content-center gap-2">
                                            <a href="<?= BASE_URL ?>/proformas/preview?id=<?= $pf['id'] ?>" class="btn btn-sm btn-outline-primary rounded-pill px-3 d-inline-flex align-items-center gap-1 shadow-sm">
                                                <span class="material-symbols-outlined" style="font-size: 16px;">visibility</span> View
                                            </a>
                                            <form action="<?= BASE_URL ?>/proformas/delete" method="POST" class="delete-form">
                                                <input type="hidden" name="id" value="<?= $pf['id'] ?>">
                                                <button type="button" class="btn btn-sm btn-outline-danger rounded-pill px-3 d-inline-flex align-items-center gap-1 shadow-sm delete-btn">
                                                    <span class="material-symbols-outlined" style="font-size: 16px;">delete</span> Delete
                                                </button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Delete Confirm Modal -->
<div class="modal fade" id="deleteConfirmModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" style="max-width: 400px;">
        <div class="modal-content border-0 shadow-lg" style="border-radius: 28px;">
            <div class="modal-body p-4">
                <h4 class="mb-3" style="font-size: 24px; color: #1f1f1f; font-weight: 400;">Delete Pro Forma?</h4>
                <p style="font-size: 14px; color: #444746; line-height: 1.5; margin-bottom: 32px;">Are you sure you want to completely delete this Pro Forma Invoice? This action cannot be undone.</p>
                <div class="d-flex justify-content-end align-items-center gap-2">
                    <button type="button" class="btn btn-link" data-bs-dismiss="modal" style="color: #0b57d0; font-weight: 500; text-decoration: none; padding: 10px 16px; border-radius: 20px;">Cancel</button>
                    <button type="button" id="confirmDeleteBtn" class="btn" style="background-color: #dc3545; color: #fff; font-weight: 500; border-radius: 20px; padding: 10px 24px; border: none;">Delete</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        let formToSubmit = null;
        const deleteModal = new bootstrap.Modal(document.getElementById('deleteConfirmModal'));

        document.querySelectorAll('.delete-btn').forEach(btn => {
            btn.addEventListener('click', function(e) {
                formToSubmit = this.closest('.delete-form');
                deleteModal.show();
            });
        });

        document.getElementById('confirmDeleteBtn').addEventListener('click', function() {
            if (formToSubmit) {
                formToSubmit.submit();
            }
        });
    });
</script>
<?php
$content = ob_get_clean();
require __DIR__ . '/../../views/layouts/main.php';
?>
